### ISSUE TITLE
Tiling a 3D dataset into 3D dimensional slices

### ISSUE THREAD

**Issue by roflmaostc** [bionanoimaging/TiledViews.jl#4]
I wanted to slice a 3D volume into tiles like:
```julia
julia> x = randn((4,4,4));

julia> tv = TiledView(x, (2,2,4), (0,0,0));

julia> size(tv) # I expected (2, 2, 4, 2, 2, 1)
(2, 2, 4, 2, 2, 2)
```
The resulting `tv` seems to access out of index regions and pads them with a default value.
Is it possible to get only a single tile in the 3rd dimension?

This also feels slightly odd:
```julia
julia> tv = TiledView(x, (2,2,1), (0,0,0)) |> size
(2, 2, 1, 2, 2, 4)

julia> tv = TiledView(x, (2,2,2), (0,0,0)) |> size
(2, 2, 2, 2, 2, 2)

julia> tv = TiledView(x, (2,2,3), (0,0,0)) |> size
(2, 2, 3, 2, 2, 2)

julia> tv = TiledView(x, (2,2,4), (0,0,0)) |> size
(2, 2, 4, 2, 2, 2)

julia> tv = TiledView(x, (2,2,5), (0,0,0)) |> size
(2, 2, 5, 2, 2, 1)
```

Thanks,
Felix

**Comment by RainerHeintzmann** [comment]
Thanks a lot. Indeed there was a bug with the calculation of the tile center. Yet, the result in the first example is still not what you expected. It is
`(2, 2, 4, 3, 3, 1)`
The reason is that the `TiledView` tries to assure that the central tile is aligned with its central pixel to the central pixel of the parent data. If you want to start without an offset, you need to supply the argument `keep_center=false`.
